### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by darksidezx** [SolarisYan/rundeck-winsmb-plugin#1]
Whenever I run a ad-hoc command on rundeck hosted on Linux to a Windows remote node, I will get the error of "Failed: NonZeroResultCode: [WinSMBexe] Result code: 127"

How do I solve this issue?

**Comment by SolarisYan** [comment]
@darksidezx  sorry late to reply. you should install the pakcage like:
>  pip install impacket
>  yum install winexe

and in your resources.xml file,with the windows node you should conf like this:
> \<node name="xxx" description="" tags="windows" hostname="xxx" osArch="" osFamily="windows" osName="windows" osVersion="" username="administrator" file-copier="WinSMBcp" node-executor="WinSMBexe" win-password-storage-path="xxx"/>

then it will work well
